### ISSUE TITLE
Unable to run on Databricks

### ISSUE THREAD

**Issue by mykolamelnykml** [StabRise/spark-pdf#10]
Need to test PDF Data Source on Databricks.

Runtime: 14.3 LTS (includes Apache Spark 3.5.0, Scala 2.12)

Current error:

Py4JJavaError: An error occurred while calling o428.showString.
: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.PartitionedFile.<init>(Lorg/apache/spark/sql/catalyst/InternalRow;Lorg/apache/spark/paths/SparkPath;JJ[Ljava/lang/String;JJLscala/collection/immutable/Map;)V
	at com.stabrise.sparkpdf.datasources.PdfPartitionedFileUtil$.$anonfun$splitFiles$1(PdfPartitionedFileUtil.scala:32)
	at com.stabrise.sparkpdf.datasources.PdfPartitionedFileUtil$.$anonfun$splitFiles$1$adapted(PdfPartitionedFileUtil.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.immutable.NumericRange.foreach(NumericRange.scala:75)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)

Full log here: [traceback.txt](https://github.com/user-attachments/files/17989288/traceback.txt)	
Example notebook: [PdfDataSourceDatabricks.zip](https://github.com/user-attachments/files/17989392/PdfDataSourceDatabricks.zip)

**Comment by kolia1985** [comment]
@irfanmaroof 
What is version of the Spark did you use?
What is version of hadoop?

For now we have build only for Spark 3.4.x.

**Comment by gaulthier** [comment]
i got the same issue, i use a spark 3.4.1 and i got this trouble when i tried a display(df) :
```
java.lang.ClassCastException: org.apache.spark.sql.execution.datasources.FileStatusWithMetadata cannot be cast to org.apache.hadoop.fs.FileStatus
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
File <command-1640794057709310>, line 7
      1 df = spark.read.format("pdf") \
      2     .option("imageType", "BINARY") \
      3     .option("resolution", "300") \
      4     .option("pagePerPartition", "8") \
      5     .option("reader", "pdfBox") \
      6     .load(filenames)
----> 7 display(df)

File /databricks/python_shell/dbruntime/display.py:87, in Display.display(self, input, *args, **kwargs)
     84         if kwargs.get('trigger'):
     85             raise Exception('Triggers can only be set for streaming queries.')
---> 87         self.add_custom_display_data("table", input._jdf)
     88 # TODO: replace this with an implementation that serves large file upload.
     89 # This version is for Serverless + Spark Connect dogfooding.
     90 elif self.spark_connect_enabled and \
     91         type(input).__module__ == 'pyspark.sql.connect.dataframe' and \
     92         type(input).__name__ == 'DataFrame':
```

**Comment by florentpousserot** [comment]
Hi, I work with Gaulthier. it seems to me that it is a runtime 13.3 LTS.

thank you for your help

**Comment by kolia1985** [comment]
@gaulthier @irfanmaroof @florentpousserot  I fixed issue with FileStatusWithMetadata and meet new one related PartitionedFile

And I can't fix it without support of Databricks, because it is using custom build of Apache Spark. I and @aviral-bhardwaj trying to connect to the some persons in Databricks for solve this issue.

If somebody has relations to the Databricks, please share your ideas how to make custom build for the Databricks environment.

Thank you.

**Comment by BernhardSchlegel** [comment]
Hey there,

thanks for your efforts! Just letting you know I raised the issue to our Databricks Account managing team and they are actively troubleshooting on their end.

Best,
Bernhard.

**Comment by kolia1985** [comment]
Hello @BernhardSchlegel 

Thank you!

com.stabrise:spark-pdf_2.12:0.1.10 version was built for Spark 3.5.0, so fixed issue with FileStatusWithMetadata.

But still present issue: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.PartitionedFile

**Comment by LaurentPrat** [comment]
Just did a test this morning, looking forward to the fix, but you say it depends on Databricks side?

java.lang.NoSuchMethodException: java.lang.NoSuchMethodError: 'void org.apache.spark.sql.execution.datasources.PartitionedFile.<init>(org.apache.spark.sql.catalyst.InternalRow, org.apache.spark.paths.SparkPath, long, long, java.lang.String[], long, long, scala.collection.immutable.Map)'

	at com.stabrise.sparkpdf.datasources.PdfPartitionedFileUtil$.$anonfun$splitFiles$1(PdfPartitionedFileUtil.scala:35)
	at com.stabrise.sparkpdf.datasources.PdfPartitionedFileUtil$.$anonfun$splitFiles$1$adapted(PdfPartitionedFileUtil.scala:29)

**Comment by aviral-bhardwaj** [comment]
Today I am connecting with databricks team on this, will also post updates

**Comment by kolia1985** [comment]
[Xiao Li](https://www.linkedin.com/in/ACoAAAD5ZnEBRFUmiKOz-zvbNrXJgoIQL0fnWoE/), suggested to created issue on Apache Spark JIRA. I file it: https://issues.apache.org/jira/browse/SPARK-50476 .

**Comment by kolia1985** [comment]
> Just did a test this morning, looking forward to the fix, but you say it depends on Databricks side?
> 
> java.lang.NoSuchMethodException: java.lang.NoSuchMethodError: 'void org.apache.spark.sql.execution.datasources.PartitionedFile.(org.apache.spark.sql.catalyst.InternalRow, org.apache.spark.paths.SparkPath, long, long, java.lang.String[], long, long, scala.collection.immutable.Map)'
> 
> ```
> at com.stabrise.sparkpdf.datasources.PdfPartitionedFileUtil$.$anonfun$splitFiles$1(PdfPartitionedFileUtil.scala:35)
> at com.stabrise.sparkpdf.datasources.PdfPartitionedFileUtil$.$anonfun$splitFiles$1$adapted(PdfPartitionedFileUtil.scala:29)
> ```

Hello @LaurentPrat 

Thank you for the test.

Yes. PartitionedFile class on the community Spark and in safe Spark on Databricks are different.

**Comment by alexott** [comment]
@grundprinzip do we have a way to support custom data sources? 

PDF is quite an important one

**Comment by mykolamelnykml** [comment]
I tested today PDF data source on Databricks. Issue is solved. It works, but need some small fixes.
But meet issue that some dependencies is not load automatically as on raw spark.


So you can try with custom build now. I attached fat jar.

And I'm working on solution and example notebook for Databricks.

**Comment by mykolamelnykml** [comment]
Create build with assembly jar: com.stabrise:spark-pdf-spark35_2.12:0.1.14

Tested it on 15.4 LTS Runtime with single node cluster.

![Image](https://github.com/user-attachments/assets/17e54ba4-34f0-4aef-a874-eafd063a1425)

![Image](https://github.com/user-attachments/assets/a2c90c6f-d049-4418-852a-e9308dd0d751)
